# Generated by Django 6.0.3 on 2026-05-30 05:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('supervisor', '主管'), ('accountant', '会计')], default='accountant', max_length=20, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('education', models.CharField(blank=True, choices=[('college', '大专'), ('bachelor', '本科'), ('master', '硕士'), ('other', '其他')], max_length=20, verbose_name='学历')),
                ('major', models.CharField(blank=True, max_length=50, verbose_name='专业')),
                ('certificate', models.CharField(choices=[('none', '无'), ('accounting', '会计证'), ('intermediate', '中级会计师'), ('senior', '高级会计师')], default='none', max_length=20, verbose_name='证书')),
                ('work_years', models.IntegerField(default=0, verbose_name='工龄')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_no', models.CharField(max_length=50, unique=True, verbose_name='客户编号')),
                ('name', models.CharField(max_length=200, verbose_name='企业名称')),
                ('nature', models.CharField(choices=[('small', '小规模纳税人'), ('general', '一般纳税人')], default='small', max_length=20, verbose_name='企业性质')),
                ('business_scope', models.TextField(blank=True, verbose_name='经营范围')),
                ('legal_person', models.CharField(blank=True, max_length=50, verbose_name='法人代表')),
                ('contact_name', models.CharField(max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='地址')),
                ('fee_start_date', models.DateField(blank=True, null=True, verbose_name='缴费开始日期')),
                ('fee_cycle', models.CharField(choices=[('monthly', '按月'), ('quarterly', '按季'), ('yearly', '按年')], default='monthly', max_length=20, verbose_name='缴费周期')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='缴费金额')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('accountant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='对接会计')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='应收日期')),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='应收金额')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='实收日期')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实收金额')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='myadmin.client', verbose_name='客户')),
            ],
            options={
                'verbose_name': '收费记录',
                'verbose_name_plural': '收费记录',
                'db_table': 'fee',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('work_type', models.CharField(choices=[('bookkeeping', '记账'), ('tax_filing', '报税'), ('invoicing', '开票'), ('consulting', '咨询'), ('other', '其他')], max_length=20, verbose_name='工作类型')),
                ('content', models.TextField(verbose_name='工作内容')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worklogs', to='myadmin.client', verbose_name='关联客户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
            ],
            options={
                'verbose_name': '工作日志',
                'verbose_name_plural': '工作日志',
                'db_table': 'worklog',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, verbose_name='月份')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='基本工资')),
                ('performance_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='绩效工资')),
                ('total_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总薪酬')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
            ],
            options={
                'verbose_name': '薪酬',
                'verbose_name_plural': '薪酬',
                'db_table': 'salary',
                'unique_together': {('user', 'month')},
            },
        ),
    ]
